export const GET_PRODUCT_INFO_LIST_REQUEST: "GET_PRODUCT_INFO_LIST_REQUEST" =
  "GET_PRODUCT_INFO_LIST_REQUEST";

export const GET_PRODUCT_INFO_LIST_SUCCESS: "GET_PRODUCT_INFO_LIST_SUCCESS" =
  "GET_PRODUCT_INFO_LIST_SUCCESS";

export const GET_PRODUCT_INFO_LIST_FAILED: "GET_PRODUCT_INFO_LIST_FAILED" =
  "GET_PRODUCT_INFO_LIST_FAILED";
